src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("payments/", include("terminusgps_payments.urls")),
    path("django-rq/", include("django_rq.urls")),
    path("", include("terminusgps_notifications.urls")),
]

terminusgps_notifications/urls.py
from django.urls import path

from . import views

app_name = "terminusgps_notifications"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("navbar/", views.NavbarView.as_view(), name="navbar"),
    path("docs/", views.DocumentationView.as_view(), name="docs"),
    path("terms/", views.TermsView.as_view(), name="terms"),
    path("source/", views.SourceCodeView.as_view(), name="source code"),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("account/", views.AccountView.as_view(), name="account"),
    path("stats/", views.CustomerStatsView.as_view(), name="stats"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path(
        "subscription/", views.SubscriptionView.as_view(), name="subscription"
    ),
    path(
        "subscriptions/create/",
        views.CustomerSubscriptionCreateView.as_view(),
        name="create subscriptions",
    ),
    path(
        "subscriptions/create/success/",
        views.CustomerSubscriptionCreateSuccessView.as_view(),
        name="create subscriptions success",
    ),
    path(
        "notifications/",
        views.NotificationsView.as_view(),
        name="notifications",
    ),
    path(
        "notifications/list/",
        views.WialonNotificationListView.as_view(),
        name="list notifications",
    ),
    path(
        "notifications/create/",
        views.WialonNotificationCreateView.as_view(),
        name="create notifications",
    ),
    path(
        "notifications/create/success/",
        views.WialonNotificationCreateSuccessView.as_view(),
        name="create notifications success",
    ),
    path(
        "notifications/<int:notification_pk>/detail/",
        views.WialonNotificationDetailView.as_view(),
        name="detail notifications",
    ),
    path(
        "notifications/<int:notification_pk>/update/",
        views.WialonNotificationUpdateView.as_view(),
        name="update notifications",
    ),
    path(
        "notifications/<int:notification_pk>/delete/",
        views.WialonNotificationDeleteView.as_view(),
        name="delete notifications",
    ),
    path(
        "notifications/units/form/",
        views.WialonNotificationUnitSelectFormView.as_view(),
        name="units form",
    ),
    path(
        "notifications/triggers/form/",
        views.WialonNotificationTriggerFormView.as_view(),
        name="triggers form",
    ),
    path(
        "notifications/triggers/parameters/form/",
        views.WialonNotificationTriggerParametersFormView.as_view(),
        name="trigger parameters form",
    ),
    path(
        "notifications/triggers/parameters/success/",
        views.WialonNotificationTriggerParametersSuccessView.as_view(),
        name="trigger parameters success",
    ),
    path(
        "packages/create/",
        views.MessagePackageCreateView.as_view(),
        name="create packages",
    ),
    path(
        "packages/list/",
        views.MessagePackageListView.as_view(),
        name="list packages",
    ),
    path(
        "packages/price/",
        views.MessagePackagePriceView.as_view(),
        name="price packages",
    ),
    path(
        "wialon/login/", views.WialonLoginView.as_view(), name="wialon login"
    ),
]

terminusgps_notifications/forms.py
from django import forms
from terminusgps_payments.models import AddressProfile, PaymentProfile


class PaymentProfileChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        if obj.credit_card is not None:
            cc = obj.credit_card
            return f"{cc.cardType} ending in {str(cc.cardNumber)[-4:]}"
        return str(obj)


class AddressProfileChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        if obj.address is not None:
            addr = obj.address
            return str(addr.address)
        return str(obj)


class CustomerSubscriptionCreationForm(forms.Form):
    payment_profile = PaymentProfileChoiceField(
        queryset=PaymentProfile.objects.all(),
        widget=forms.widgets.Select(
            attrs={"class": "border bg-gray-50 rounded p-2"}
        ),
    )
    address_profile = AddressProfileChoiceField(
        queryset=AddressProfile.objects.all(),
        widget=forms.widgets.Select(
            attrs={"class": "border bg-gray-50 rounded p-2"}
        ),
    )
    consent = forms.BooleanField(
        initial=False,
        widget=forms.widgets.CheckboxInput(
            attrs={"class": "accent-terminus-red-700"}
        ),
    )

terminusgps_notifications/forms/subscriptions.py
from django import forms
from django.conf import settings
from terminusgps_payments.forms import (
    AddressProfileChoiceField,
    PaymentProfileChoiceField,
)
from terminusgps_payments.models import AddressProfile, PaymentProfile

WIDGET_CSS_CLASS = (
    settings.WIDGET_CSS_CLASS
    if hasattr(settings, "WIDGET_CSS_CLASS")
    else "peer p-2 rounded border border-current bg-gray-50 dark:bg-gray-600 user-invalid:bg-red-50 user-invalid:text-red-600"
)


class CustomerSubscriptionCreationForm(forms.Form):
    payment_profile = PaymentProfileChoiceField(
        queryset=PaymentProfile.objects.none(),
        widget=forms.widgets.Select(attrs={"class": WIDGET_CSS_CLASS}),
    )
    address_profile = AddressProfileChoiceField(
        queryset=AddressProfile.objects.none(),
        widget=forms.widgets.Select(attrs={"class": WIDGET_CSS_CLASS}),
    )
    consent = forms.BooleanField(
        initial=False,
        widget=forms.widgets.CheckboxInput(
            attrs={"class": "accent-terminus-red-700"}
        ),
    )

terminusgps_notifications/views/customers.py
import decimal
import typing

from authorizenet import apicontractsv1
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db import transaction
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import cache_control, cache_page
from django.views.generic import FormView, RedirectView, TemplateView
from terminusgps.authorizenet.service import (
    AuthorizenetControllerExecutionError,
)
from terminusgps.mixins import HtmxTemplateResponseMixin
from terminusgps_payments.models import (
    AddressProfile,
    PaymentProfile,
    Subscription,
)
from terminusgps_payments.services import AuthorizenetService

from terminusgps_notifications import services
from terminusgps_notifications.forms import CustomerSubscriptionCreationForm
from terminusgps_notifications.models import WialonToken


@method_decorator(cache_page(timeout=60 * 15), name="dispatch")
@method_decorator(cache_control(private=True), name="dispatch")
class DashboardView(
    LoginRequiredMixin, HtmxTemplateResponseMixin, TemplateView
):
    content_type = "text/html"
    extra_context = {
        "title": "Dashboard",
        "subtitle": "We know where ours are... do you?",
    }
    http_method_names = ["get"]
    partial_template_name = (
        "terminusgps_notifications/customers/partials/_dashboard.html"
    )
    template_name = "terminusgps_notifications/customers/dashboard.html"

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`has_subscription` to the view."""
        customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        token = (
            services.get_wialon_token(request.user)
            if hasattr(request, "user")
            else None
        )
        subscription = (
            getattr(customer, "subscription")
            if customer is not None and hasattr(customer, "subscription")
            else None
        )
        self.customer = customer
        self.has_token = bool(token)
        self.has_subscription = bool(subscription)
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`has_subscription` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        context["has_token"] = self.has_token
        context["has_subscription"] = self.has_subscription
        return context


@method_decorator(cache_page(timeout=60 * 15), name="dispatch")
@method_decorator(cache_control(private=True), name="dispatch")
class AccountView(LoginRequiredMixin, HtmxTemplateResponseMixin, TemplateView):
    content_type = "text/html"
    extra_context = {"title": "Account"}
    http_method_names = ["get"]
    partial_template_name = (
        "terminusgps_notifications/customers/partials/_account.html"
    )
    template_name = "terminusgps_notifications/customers/account.html"

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`login_params` to the view."""
        customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        token = (
            services.get_wialon_token(request.user)
            if hasattr(request, "user")
            else None
        )
        login_params = (
            services.get_wialon_login_parameters(request.user)
            if hasattr(request, "user")
            else None
        )
        self.customer = customer
        self.has_token = bool(token)
        self.login_params = login_params
        return super().setup(request, *args, **kwargs)

    @transaction.atomic
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """Saves a Wialon API token for the user based on the ``user_name`` and ``access_token`` path parameters."""
        if hasattr(request, "user") and self.customer is not None:
            user = getattr(request, "user")
            access_token = request.GET.get("access_token")
            if all(
                [
                    access_token,
                    hasattr(user, "username"),
                    getattr(user, "username") == self.customer.user.username,
                ]
            ):
                if hasattr(self.customer, "token"):
                    old_token = getattr(self.customer, "token")
                    old_token.delete()
                new_token = WialonToken()
                new_token.name = access_token
                new_token.customer = self.customer
                new_token.save()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`login_params` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        context["has_token"] = self.has_token
        context["login_params"] = self.login_params
        return context


class SubscriptionView(
    LoginRequiredMixin, HtmxTemplateResponseMixin, TemplateView
):
    content_type = "text/html"
    extra_context = {"title": "Subscription"}
    http_method_names = ["get"]
    partial_template_name = (
        "terminusgps_notifications/customers/partials/_subscription.html"
    )
    template_name = "terminusgps_notifications/customers/subscription.html"

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer` to the view."""
        self.customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        return context


class NotificationsView(
    LoginRequiredMixin, HtmxTemplateResponseMixin, TemplateView
):
    content_type = "text/html"
    extra_context = {"title": "Notifications"}
    http_method_names = ["get"]
    partial_template_name = (
        "terminusgps_notifications/customers/partials/_notifications.html"
    )
    template_name = "terminusgps_notifications/customers/notifications.html"

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`has_subscription` to the view."""
        self.customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        self.has_token = bool(
            services.get_wialon_token(request.user)
            if hasattr(request, "user")
            else None
        )
        self.has_subscription = (
            bool(self.customer.subscription) if self.customer else False
        )
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`has_subscription` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        context["has_token"] = self.has_token
        context["has_subscription"] = self.has_subscription
        return context


class CustomerSubscriptionCreateView(
    LoginRequiredMixin, HtmxTemplateResponseMixin, FormView
):
    content_type = "text/html"
    extra_context = {
        "title": "Create Subscription",
        "setup_fee": settings.NOTIFICATIONS_SETUP_FEE,
    }
    form_class = CustomerSubscriptionCreationForm
    http_method_names = ["get", "post"]
    partial_template_name = "terminusgps_notifications/customers/partials/_create_subscription.html"
    template_name = (
        "terminusgps_notifications/customers/create_subscription.html"
    )
    success_url = reverse_lazy(
        "terminusgps_notifications:create subscriptions success"
    )

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer` and :py:attr:`anet_service` to the view."""
        self.customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        self.anet_service = AuthorizenetService()
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        context["total"] = self.customer.subtotal + context["setup_fee"]
        return context

    def get_form(self, form_class=None) -> CustomerSubscriptionCreationForm:
        """Sets customer payment profiles and address profiles in the form."""
        form = super().get_form(form_class=form_class)
        payment_qs = PaymentProfile.objects.for_user(self.request.user)
        address_qs = AddressProfile.objects.for_user(self.request.user)
        pprofile_field = form.fields["payment_profile"]
        aprofile_field = form.fields["address_profile"]
        pprofile_field.queryset = payment_qs

terminusgps_notifications/templates/terminusgps_notifications/partials/_home.html
<div class="flex flex-col gap-8">
    <section class="mx-4 flex flex-col gap-4 text-pretty">
        <h2 class="-mx-4 text-lg font-semibold text-terminus-red-500 dark:text-terminus-red-100">Live Notifications, Instantly Delivered</h2>
        <p>Stay connected in real time. Receive live alerts straight to your mobile device the moment something important happens. Fully customizable so you only get the notifications that matter most to your operation.</p>
    </section>
    <section class="mx-4 flex flex-col gap-4 text-pretty">
        <h2 class="-mx-4 text-lg font-semibold text-terminus-red-500 dark:text-terminus-red-100">Custom Notification Management</h2>
        <p>Create, edit and organize alerts for each of your units.</p>
    </section>
    <section class="mx-4 flex flex-col gap-4 text-pretty">
        <h2 class="-mx-4 text-lg font-semibold text-terminus-red-500 dark:text-terminus-red-100">Simplified Payment Manager</h2>
        <p>Manage your notification subscriptions and payments all in one place. Track your active subscription, upgrade instantly and scale your usage as your needs grow.</p>
    </section>
    <section class="mx-4 flex flex-col gap-4 text-pretty">
        <h2 class="-mx-4 text-lg font-semibold text-terminus-red-500 dark:text-terminus-red-100">Comprehensive Dashboard</h2>
        <p>Monitor how your team uses notifications with a clear, data-driven dashboard. Track total alerts sent and optimize your notifications for better efficiency and cost control.</p>
    </section>
    <section class="mx-4 flex flex-col gap-4 text-pretty">
        <h2 class="-mx-4 text-lg font-semibold text-terminus-red-500 dark:text-terminus-red-100">Dedicated In-House Support</h2>
        <p>Our expert <a href="mailto:support@terminusgps.com" class="w-fit decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white">support team</a> is always ready to help with account questions, billing issues or technical setup.</p>
    </section>
</div>

terminusgps_notifications/templates/terminusgps_notifications/partials/_logged_out.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
<div class="flex flex-col gap-2">
    <p>You were logged out successfully.</p>
    <p>See you next time!</p>
</div>
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/partials/_navbar.html
{% load static %}
<nav class="flex justify-between bg-stone-100 text-gray-800 drop-shadow dark:bg-gray-800">
    <a href="{% url 'terminusgps_notifications:home' %}" class="group flex items-center space-x-1">
        <img src="{% static 'terminusgps_notifications/icon/logo-waypoint.svg' %}" class="size-16 animate-coin-slow group-hover:animate-none">
        <img src="{% static 'terminusgps_notifications/icon/logo-text.svg' %}" class="size-24">
    </a>
    {% if user and user.is_authenticated %}
    <div class="mx-4 flex items-center gap-2">
        <a href="{% url 'terminusgps_notifications:dashboard' %}" class="flex items-center gap-2 rounded border border-current bg-gray-300 px-4 py-2 transition-colors duration-300 ease-in-out hover:bg-gray-100 hover:text-terminus-red-300">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="relative size-6 transition-colors duration-300 ease-in-out group-hover:text-terminus-red-300">
                <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
            </svg>
            <p class="hidden md:flex">{{ user.username }}</p>
        </a>
        <button hx-post="{% url 'terminusgps_notifications:logout' %}" class="flex items-center gap-2 rounded border border-current bg-gray-300 px-4 py-2 transition-colors duration-300 ease-in-out hover:bg-gray-100 hover:text-terminus-red-300 cursor-pointer" hx-headers='{"x-csrftoken": "{{ csrf_token }}"}' hx-trigger="click" hx-target="body" hx-swap="outerHTML" hx-confirm="Are you sure you want to logout?">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15m3 0 3-3m0 0-3-3m3 3H9" />
            </svg>
            <p class="hidden md:flex">Logout</p>
        </button>
    </div>
    {% else %}
    <div class="mx-4 flex items-center gap-2">
        <a href="{% url 'terminusgps_notifications:register' %}" class="flex items-center gap-2 rounded border border-current bg-gray-300 px-4 py-2 transition-colors duration-300 ease-in-out hover:bg-gray-100 hover:text-terminus-red-300">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
            </svg>
            <p class="hidden md:flex">Register</p>
        </a>
        <a href="{% url 'terminusgps_notifications:login' %}" class="flex items-center gap-2 rounded border border-current bg-gray-300 px-4 py-2 transition-colors duration-300 ease-in-out hover:bg-gray-100 hover:text-terminus-red-300">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0 0 13.5 3h-6a2.25 2.25 0 0 0-2.25 2.25v13.5A2.25 2.25 0 0 0 7.5 21h6a2.25 2.25 0 0 0 2.25-2.25V15M12 9l-3 3m0 0 3 3m-3-3h12.75" />
            </svg>
            <p class="hidden md:flex">Login</p>
        </a>
    </div>
    {% endif %}
</nav>

terminusgps_notifications/templates/terminusgps_notifications/partials/_register.html
<form class="flex flex-col gap-4" action="{% url 'terminusgps_notifications:register' %}" method="post">
    {% if form.non_field_errors %}
    <div class="p-2 bg-red-200 text-red-700 animate-jiggle border border-current rounded">
        <div class="flex gap-2 items-center">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 text-red-700 fill-red-50 animate-pulse">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9 3.75h.008v.008H12v-.008Z" />
            </svg>
            {{ form.non_field_errors }}
        </div>
    </div>
    {% endif %}
    {% csrf_token %}
    <section class="flex flex-col gap-2 justify-between md:flex-row">
        <section class="flex flex-col gap-2 w-full">
            {{ form.first_name }}
            <label class="order-first font-semibold peer-user-invalid:text-red-800" for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
            <p class="text-sm peer-user-invalid:text-red-600" id="{{ form.first_name.id_for_label }}_helptext">{{ form.first_name.help_text }}</p>
            {% if form.first_name.errors %}<div class="animate-jiggle font-italic">{{ form.first_name.errors }}</div>{% endif %}
        </section>
        <section class="flex flex-col gap-2 w-full">
            {{ form.last_name }}
            <label class="order-first font-semibold peer-user-invalid:text-red-800" for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
            <p class="text-sm peer-user-invalid:text-red-600" id="{{ form.last_name.id_for_label }}_helptext">{{ form.last_name.help_text }}</p>
            {% if form.last_name.errors %}<div class="animate-jiggle font-italic">{{ form.last_name.errors }}</div>{% endif %}
        </section>
    </section>
    <section class="flex flex-col gap-2">
        {{ form.company_name }}
        <label class="order-first peer-user-invalid:text-red-800" for="{{ form.company_name.id_for_label }}">{{ form.company_name.label }}</label>
        <p class="text-sm peer-user-invalid:text-red-600" id="{{ form.company_name.id_for_label }}_helptext">{{ form.company_name.help_text|safe }}</p>
        {% if form.company_name.errors %}<div class="animate-jiggle font-italic">{{ form.company_name.errors }}</div>{% endif %}
    </section>
    <section class="flex flex-col gap-2">
        {{ form.username }}
        <label class="order-first font-semibold peer-user-invalid:text-red-800" for="{{ form.username.id_for_label }}">Email Address</label>
        <p class="text-sm peer-user-invalid:text-red-600" id="{{ form.username.id_for_label }}_helptext">{{ form.username.help_text }}</p>
        {% if form.username.errors %}<div class="animate-jiggle font-italic">{{ form.username.errors }}</div>{% endif %}
    </section>
    <section class="flex flex-col gap-2">
        {{ form.password1 }}
        <label class="order-first font-semibold peer-user-invalid:text-red-800" for="{{ form.password1.id_for_label }}">Password</label>
        <p class="text-sm peer-user-invalid:text-red-600" id="{{ form.password1.id_for_label }}_helptext">{{ form.password1.help_text }}</p>
        {% if form.password1.errors %}<div class="animate-jiggle font-italic">{{ form.password1.errors }}</div>{% endif %}
    </section>
    <section class="flex flex-col gap-2">
        {{ form.password2 }}
        <label class="order-first font-semibold peer-user-invalid:text-red-800" for="{{ form.password2.id_for_label }}">Repeat Password</label>
        <p class="text-sm peer-user-invalid:text-red-600" id="{{ form.password2.id_for_label }}_helptext">{{ form.password2.help_text }}</p>
        {% if form.password2.errors %}<div class="animate-jiggle font-italic">{{ form.password2.errors }}</div>{% endif %}
    </section>
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    <div class="flex flex-col gap-4">
        <section class="flex gap-2 items-center">
            {{ form.consent }}
            <label class="peer-user-invalid:text-red-800" for="{{ form.consent.id_for_label }}">By checking this box, you agree to our <a href="{% url 'terminusgps_notifications:terms' %}" hx-boost="true" hx-inherit="false" class="w-fit decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white">terms of use</a> and <a href="{% url 'terminusgps_notifications:privacy' %}" hx-boost="true" hx-inherit="false" class="w-fit decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white">privacy policy</a>.</label>
            {% if form.consent.errors %}<div class="animate-jiggle font-italic">{{ form.consent.errors }}</div>{% endif %}
        </section>
        <button type="submit" class="flex w-full cursor-pointer items-center justify-center gap-2 rounded border border-terminus-red-900 bg-terminus-red-800 p-2 text-center text-white transition-colors duration-300 ease-in-out hover:bg-terminus-red-400">Register</button>
        <p class="text-center">Already have an account? Click <a href="{% url 'terminusgps_notifications:login' %}" hx-boost="true" hx-inherit="false" class="w-fit decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white">here</a> to login.</p>
    </div>
</form>