src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("payments/", include("terminusgps_payments.urls")),
    path("django-rq/", include("django_rq.urls")),
    path("", include("terminusgps_notifications.urls")),
]

terminusgps_notifications/urls.py
from django.urls import path

from . import views

app_name = "terminusgps_notifications"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("navbar/", views.NavbarView.as_view(), name="navbar"),
    path("docs/", views.DocumentationView.as_view(), name="docs"),
    path("terms/", views.TermsView.as_view(), name="terms"),
    path("source/", views.SourceCodeView.as_view(), name="source code"),
    path("privacy/", views.PrivacyView.as_view(), name="privacy"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("account/", views.AccountView.as_view(), name="account"),
    path("stats/", views.CustomerStatsView.as_view(), name="stats"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path(
        "subscription/", views.SubscriptionView.as_view(), name="subscription"
    ),
    path(
        "subscriptions/create/",
        views.CustomerSubscriptionCreateView.as_view(),
        name="create subscriptions",
    ),
    path(
        "subscriptions/create/success/",
        views.CustomerSubscriptionCreateSuccessView.as_view(),
        name="create subscriptions success",
    ),
    path(
        "notifications/",
        views.NotificationsView.as_view(),
        name="notifications",
    ),
    path(
        "notifications/list/",
        views.WialonNotificationListView.as_view(),
        name="list notifications",
    ),
    path(
        "notifications/create/",
        views.WialonNotificationCreateView.as_view(),
        name="create notifications",
    ),
    path(
        "notifications/create/success/",
        views.WialonNotificationCreateSuccessView.as_view(),
        name="create notifications success",
    ),
    path(
        "notifications/<int:notification_pk>/detail/",
        views.WialonNotificationDetailView.as_view(),
        name="detail notifications",
    ),
    path(
        "notifications/<int:notification_pk>/update/",
        views.WialonNotificationUpdateView.as_view(),
        name="update notifications",
    ),
    path(
        "notifications/<int:notification_pk>/delete/",
        views.WialonNotificationDeleteView.as_view(),
        name="delete notifications",
    ),
    path(
        "notifications/units/form/",
        views.WialonNotificationUnitSelectFormView.as_view(),
        name="units form",
    ),
    path(
        "notifications/triggers/form/",
        views.WialonNotificationTriggerFormView.as_view(),
        name="triggers form",
    ),
    path(
        "notifications/triggers/parameters/form/",
        views.WialonNotificationTriggerParametersFormView.as_view(),
        name="trigger parameters form",
    ),
    path(
        "notifications/triggers/parameters/success/",
        views.WialonNotificationTriggerParametersSuccessView.as_view(),
        name="trigger parameters success",
    ),
    path(
        "packages/create/",
        views.MessagePackageCreateView.as_view(),
        name="create packages",
    ),
    path(
        "packages/list/",
        views.MessagePackageListView.as_view(),
        name="list packages",
    ),
    path(
        "packages/price/",
        views.MessagePackagePriceView.as_view(),
        name="price packages",
    ),
    path(
        "wialon/login/", views.WialonLoginView.as_view(), name="wialon login"
    ),
]

terminusgps_notifications/forms.py
from django import forms
from terminusgps_payments.models import AddressProfile, PaymentProfile


class PaymentProfileChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        if obj.credit_card is not None:
            cc = obj.credit_card
            return f"{cc.cardType} ending in {str(cc.cardNumber)[-4:]}"
        return str(obj)


class AddressProfileChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        if obj.address is not None:
            addr = obj.address
            return str(addr.address)
        return str(obj)


class CustomerSubscriptionCreationForm(forms.Form):
    payment_profile = PaymentProfileChoiceField(
        queryset=PaymentProfile.objects.all(),
        widget=forms.widgets.Select(
            attrs={"class": "border bg-gray-50 rounded p-2"}
        ),
    )
    address_profile = AddressProfileChoiceField(
        queryset=AddressProfile.objects.all(),
        widget=forms.widgets.Select(
            attrs={"class": "border bg-gray-50 rounded p-2"}
        ),
    )
    consent = forms.BooleanField(
        initial=False,
        widget=forms.widgets.CheckboxInput(
            attrs={"class": "accent-terminus-red-700"}
        ),
    )

terminusgps_notifications/forms/subscriptions.py
from django import forms
from django.conf import settings
from terminusgps_payments.forms import (
    AddressProfileChoiceField,
    PaymentProfileChoiceField,
)
from terminusgps_payments.models import AddressProfile, PaymentProfile

WIDGET_CSS_CLASS = (
    settings.WIDGET_CSS_CLASS
    if hasattr(settings, "WIDGET_CSS_CLASS")
    else "peer p-2 rounded border border-current bg-gray-50 dark:bg-gray-600 user-invalid:bg-red-50 user-invalid:text-red-600"
)


class CustomerSubscriptionCreationForm(forms.Form):
    payment_profile = PaymentProfileChoiceField(
        queryset=PaymentProfile.objects.none(),
        widget=forms.widgets.Select(attrs={"class": WIDGET_CSS_CLASS}),
    )
    address_profile = AddressProfileChoiceField(
        queryset=AddressProfile.objects.none(),
        widget=forms.widgets.Select(attrs={"class": WIDGET_CSS_CLASS}),
    )
    consent = forms.BooleanField(
        initial=False,
        widget=forms.widgets.CheckboxInput(
            attrs={"class": "accent-terminus-red-700"}
        ),
    )

terminusgps_notifications/views/customers.py
import decimal
import typing

from authorizenet import apicontractsv1
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db import transaction
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views.decorators.cache import cache_control, cache_page
from django.views.generic import FormView, RedirectView, TemplateView
from terminusgps.authorizenet.service import (
    AuthorizenetControllerExecutionError,
)
from terminusgps.mixins import HtmxTemplateResponseMixin
from terminusgps_payments.models import (
    AddressProfile,
    PaymentProfile,
    Subscription,
)
from terminusgps_payments.services import AuthorizenetService

from terminusgps_notifications import services
from terminusgps_notifications.forms import CustomerSubscriptionCreationForm
from terminusgps_notifications.models import WialonToken


@method_decorator(cache_page(timeout=60 * 15), name="dispatch")
@method_decorator(cache_control(private=True), name="dispatch")
class DashboardView(
    LoginRequiredMixin, HtmxTemplateResponseMixin, TemplateView
):
    content_type = "text/html"
    extra_context = {
        "title": "Dashboard",
        "subtitle": "We know where ours are... do you?",
    }
    http_method_names = ["get"]
    partial_template_name = (
        "terminusgps_notifications/customers/partials/_dashboard.html"
    )
    template_name = "terminusgps_notifications/customers/dashboard.html"

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`has_subscription` to the view."""
        customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        token = (
            services.get_wialon_token(request.user)
            if hasattr(request, "user")
            else None
        )
        subscription = (
            getattr(customer, "subscription")
            if customer is not None and hasattr(customer, "subscription")
            else None
        )
        self.customer = customer
        self.has_token = bool(token)
        self.has_subscription = bool(subscription)
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`has_subscription` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        context["has_token"] = self.has_token
        context["has_subscription"] = self.has_subscription
        return context


@method_decorator(cache_page(timeout=60 * 15), name="dispatch")
@method_decorator(cache_control(private=True), name="dispatch")
class AccountView(LoginRequiredMixin, HtmxTemplateResponseMixin, TemplateView):
    content_type = "text/html"
    extra_context = {"title": "Account"}
    http_method_names = ["get"]
    partial_template_name = (
        "terminusgps_notifications/customers/partials/_account.html"
    )
    template_name = "terminusgps_notifications/customers/account.html"

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`login_params` to the view."""
        customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        token = (
            services.get_wialon_token(request.user)
            if hasattr(request, "user")
            else None
        )
        login_params = (
            services.get_wialon_login_parameters(request.user)
            if hasattr(request, "user")
            else None
        )
        self.customer = customer
        self.has_token = bool(token)
        self.login_params = login_params
        return super().setup(request, *args, **kwargs)

    @transaction.atomic
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """Saves a Wialon API token for the user based on the ``user_name`` and ``access_token`` path parameters."""
        if hasattr(request, "user") and self.customer is not None:
            user = getattr(request, "user")
            access_token = request.GET.get("access_token")
            if all(
                [
                    access_token,
                    hasattr(user, "username"),
                    getattr(user, "username") == self.customer.user.username,
                ]
            ):
                if hasattr(self.customer, "token"):
                    old_token = getattr(self.customer, "token")
                    old_token.delete()
                new_token = WialonToken()
                new_token.name = access_token
                new_token.customer = self.customer
                new_token.save()
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`login_params` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        context["has_token"] = self.has_token
        context["login_params"] = self.login_params
        return context


class SubscriptionView(
    LoginRequiredMixin, HtmxTemplateResponseMixin, TemplateView
):
    content_type = "text/html"
    extra_context = {"title": "Subscription"}
    http_method_names = ["get"]
    partial_template_name = (
        "terminusgps_notifications/customers/partials/_subscription.html"
    )
    template_name = "terminusgps_notifications/customers/subscription.html"

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer` to the view."""
        self.customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        return context


class NotificationsView(
    LoginRequiredMixin, HtmxTemplateResponseMixin, TemplateView
):
    content_type = "text/html"
    extra_context = {"title": "Notifications"}
    http_method_names = ["get"]
    partial_template_name = (
        "terminusgps_notifications/customers/partials/_notifications.html"
    )
    template_name = "terminusgps_notifications/customers/notifications.html"

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`has_subscription` to the view."""
        self.customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        self.has_token = bool(
            services.get_wialon_token(request.user)
            if hasattr(request, "user")
            else None
        )
        self.has_subscription = (
            bool(self.customer.subscription) if self.customer else False
        )
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer`, :py:attr:`has_token` and :py:attr:`has_subscription` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        context["has_token"] = self.has_token
        context["has_subscription"] = self.has_subscription
        return context


class CustomerSubscriptionCreateView(
    LoginRequiredMixin, HtmxTemplateResponseMixin, FormView
):
    content_type = "text/html"
    extra_context = {
        "title": "Create Subscription",
        "setup_fee": settings.NOTIFICATIONS_SETUP_FEE,
    }
    form_class = CustomerSubscriptionCreationForm
    http_method_names = ["get", "post"]
    partial_template_name = "terminusgps_notifications/customers/partials/_create_subscription.html"
    template_name = (
        "terminusgps_notifications/customers/create_subscription.html"
    )
    success_url = reverse_lazy(
        "terminusgps_notifications:create subscriptions success"
    )

    def setup(self, request: HttpRequest, *args, **kwargs) -> None:
        """Adds :py:attr:`customer` and :py:attr:`anet_service` to the view."""
        self.customer = (
            services.get_customer(request.user)
            if hasattr(request, "user")
            else None
        )
        self.anet_service = AuthorizenetService()
        return super().setup(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict[str, typing.Any]:
        """Adds :py:attr:`customer` to the view context."""
        context: dict[str, typing.Any] = super().get_context_data(**kwargs)
        context["customer"] = self.customer
        context["total"] = self.customer.subtotal + context["setup_fee"]
        return context

    def get_form(self, form_class=None) -> CustomerSubscriptionCreationForm:
        """Sets customer payment profiles and address profiles in the form."""
        form = super().get_form(form_class=form_class)
        payment_qs = PaymentProfile.objects.for_user(self.request.user)
        address_qs = AddressProfile.objects.for_user(self.request.user)
        pprofile_field = form.fields["payment_profile"]
        aprofile_field = form.fields["address_profile"]
        pprofile_field.queryset = payment_qs

terminusgps_notifications/templates/terminusgps_notifications/account.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_account.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/contact.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_contact.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/create_subscription.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_create_subscription.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/dashboard.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_dashboard.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/footer.html
<footer class="w-full border-t border-gray-200 bg-stone-100 p-4 drop-shadow md:flex md:items-center md:justify-between md:p-6 dark:border-gray-600 dark:bg-gray-800">
    <span class="text-sm text-gray-800 sm:text-center dark:text-gray-100">© 2025 <a href="https://terminusgps.com/" class="decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white">Terminus GPS, LLC</a>. All Rights Reserved.</span>
    <ul hx-boost="true" class="mt-3 flex flex-wrap items-center text-sm font-medium text-gray-600 sm:mt-0 dark:text-gray-400">
        <li><a href="{% url 'terminusgps_notifications:contact' %}" class="me-4 decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white md:me-6">Contact</a></li>
        <li><a href="{% url 'terminusgps_notifications:docs' %}" class="me-4 decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white md:me-6" hx-boost="false">Docs</a></li>
        <li><a href="{% url 'terminusgps_notifications:privacy' %}" class="me-4 decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white md:me-6">Privacy</a></li>
        <li><a href="{% url 'terminusgps_notifications:source code' %}" class="me-4 decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white md:me-6" hx-boost="false">Source</a></li>
        <li><a href="{% url 'terminusgps_notifications:terms' %}" class="me-4 decoration text-terminus-red-200 underline decoration-terminus-black underline-offset-4 hover:text-terminus-red-100 hover:decoration-dotted dark:decoration-white md:me-6">Terms</a></li>
    </ul>
</footer>

terminusgps_notifications/templates/terminusgps_notifications/home.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_home.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <title>{% if title %}{{ title }} | {% endif %}Terminus GPS Notifications</title>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <link rel="icon" href="{% static 'terminusgps_notifications/favicon.ico' %}">
        <link rel="stylesheet" href="{% static 'terminusgps_notifications/css/output.css' %}">
        <script src="{% static 'terminusgps_notifications/js/htmx.min.js' %}" defer></script>
    </head>
    <body class="text-gray-800 dark:text-gray-100" style='background-image: url("{% static 'terminusgps_notifications/img/background-light.png' %}");'>
        <nav class="flex justify-between bg-stone-100 text-gray-800 drop-shadow dark:bg-gray-800" hx-get="{% url 'terminusgps_notifications:navbar' %}" hx-target="this" hx-trigger="load" hx-swap="outerHTML">
            <a href="{% url 'terminusgps_notifications:home' %}" class="group flex items-center space-x-1">
                <img src="{% static 'terminusgps_notifications/icon/logo-waypoint.svg' %}" class="size-16 animate-coin-slow group-hover:animate-none">
                <img src="{% static 'terminusgps_notifications/icon/logo-text.svg' %}" class="size-24">
            </a>
            <div class="mx-4 flex items-center gap-2"></div>
        </nav>
        <main class="container mx-auto -mt-2 max-w-screen-lg" hx-indicator="#loading">
            <div class="border-lr mx-8 border-gray-600 bg-stone-100 dark:bg-gray-800">
                <section class="mt-2 flex flex-col gap-2 bg-gray-200 p-8 shadow-inner dark:bg-gray-600">
                    <div class="flex items-center gap-2">
                        <h2 class="text-xl font-bold md:text-2xl">{{ title }}</h2>
                        <svg id="loading" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="htmx-indicator size-8 animate-spin">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0 3.181 3.183a8.25 8.25 0 0 0 13.803-3.7M4.031 9.865a8.25 8.25 0 0 1 13.803-3.7l3.181 3.182m0-4.991v4.99" />
                        </svg>
                    </div>
                    {% if subtitle %}<h3 class="font-light md:text-lg">{{ subtitle }}</h3>{% endif %}
                </section>
                <section class="p-8">
                    {% block content %}{% endblock content %}
                </section>
            </div>
        </main>
        {% include "terminusgps_notifications/footer.html" %}
    </body>
</html>

terminusgps_notifications/templates/terminusgps_notifications/navbar.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_navbar.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/notifications.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_notifications.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/privacy.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_privacy.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/register.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_register.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/stats.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_stats.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/subscription.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_subscription.html" %}
{% endblock content %}

terminusgps_notifications/templates/terminusgps_notifications/wialon_callback.html
{% extends "terminusgps_notifications/layout.html" %}
{% block content %}
{% include "terminusgps_notifications/partials/_wialon_callback.html" %}
{% endblock content %}